# Use a imagem oficial do Node.js na versão 18 como base
FROM node:18

# Define o diretório de trabalho dentro do container
WORKDIR /app

# Copia apenas os arquivos de dependências para instalar primeiro, 
# melhorando o cache em etapas subsequentes
COPY package*.json ./

# Instala as dependências do projeto
RUN npm install --production

# Copia o restante do código da aplicação para o diretório de trabalho
COPY . .

# Expõe a porta que o container vai utilizar (porta 3000)
EXPOSE 3000

# Define o comando padrão para iniciar a aplicação
CMD ["npm", "start"]
